name = "femaleperiodsupport"
main = "src/index.js"
compatibility_date = "2023-02-18"
kv_namespaces=[
    { binding = "static_data", id = "cae8bc215f264d9385ad8968a1ff05f2", preview_id = "96681e28da664104975fea96cab8e57b"}
]